service: aws-scheduler
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    REGION: us-east-1
    STAGE: ${opt:stage, 'dev'}
    SERVICE: aws-scheduler
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:PutRule
            - events:PutTargets
            - events:PutPermission
            - lambda:InvokeFunction
            - lambda:AddPermission
            - events:InvokeLambdaFunction
          Resource: "*"

functions:
  createScheduler:
    handler: index.handler
  hello:
    handler: hello.handler
  world:
    handler: world.handler
